Refactoring
alercebroker/cats_service pull request #19
Opened 2023-01-23 20:04 UTC by mcaceres2017

Closes #18

2023-01-24 14:59 UTC, dirodriguezm requested changes

2023-01-24 14:59 UTC, dirodriguezm commented on .env
> +CATALOGS=catalog
este archivo no debería ir en git, se puede agregar al gitignore

2023-01-24 14:59 UTC, dirodriguezm commented on .gitignore
> +tests/__pycache__/
Se puede agregar todos los __pycache__ con `/__pycache__`

2023-01-24 14:59 UTC, dirodriguezm commented on build/lib/tests/results_service.py
> +    }
Corregir el formateo de este archivo. Usar https://pypi.org/project/black/

2023-01-24 14:59 UTC, dirodriguezm commented on setup.py
> +setup(name="cats_service", packages=find_packages())
Duda: por qué agregar un setup ?

2023-01-24 14:59 UTC, dirodriguezm commented on src.egg-info/PKG-INFO
> +License-File: LICENSE
Agregar a gitignore

2023-01-24 14:59 UTC, dirodriguezm commented on src.egg-info/SOURCES.txt
> +tests/test_service.py
Agregar a gitignore

2023-01-24 14:59 UTC, dirodriguezm commented on src.egg-info/dependency_links.txt
> +
Agregar a gitignore

2023-01-24 14:59 UTC, dirodriguezm commented on src.egg-info/top_level.txt
> +tests
Agregar a gitignore

2023-01-24 14:59 UTC, dirodriguezm commented on tests/results_service.py
> +scsr2 = {'RA': {'units': 'deg', 'values': [1.016179215453705]}, 'Dec': {'units': 'deg', 'values': [-0.011691666358472456]}, 'SideProb': {'units': ' ', 'values': [0.014053002]}, 'Fpeak': {'units': 'mJ
Formateo del archivo. Usar https://pypi.org/project/black/

2023-01-24 14:59 UTC, dirodriguezm commented on text.txt
> +[[0.0177356731, -0.000204058073, 0.014053002, 10.4300003, 10.716876, 0.108766742, 1.63, 0.0, 33.9000015, 6.53999996, 5.42999983, 6.30000019, 2450019.71, 2452482.94]] ['RA', 'Dec', 'SideProb', 'Fpeak'
Para qué es este archivo ?

2023-01-24 14:59 UTC, dirodriguezm commented on text2.txt
> +{'RA': {'units': 'deg', 'values': [1.016179215453705]}, 'Dec': {'units': 'deg', 'values': [-0.011691666358472456]}, 'SideProb': {'units': ' ', 'values': [0.014053002]}, 'Fpeak': {'units': 'mJy', 'val
Para qué es este archivo ?

2023-01-24 15:24 UTC, mcaceres2017 commented on .env
> +CATALOGS=catalog
Agregado a gitignore

2023-01-24 15:24 UTC, mcaceres2017 commented on .gitignore
> +tests/__pycache__/
Lo cambie a **/__pycache__ y ya no se detectan los pycache

2023-01-24 15:28 UTC, mcaceres2017 commented on setup.py
> +setup(name="cats_service", packages=find_packages())
Al realizar los test unos dias atras, pytets no detectaba la libreria catsHTM, y ocupamos este archivo como solución temporal, pero luego instalamos catsHTM con pip y se soluciono, por lo tanto, elimine este archivo.

2023-01-24 15:30 UTC, mcaceres2017 commented on src.egg-info/PKG-INFO
> +License-File: LICENSE
Agregado con `src/src.egg-info`

2023-01-24 15:30 UTC, mcaceres2017 commented on src.egg-info/dependency_links.txt
> +
Agregado con `src/src.egg-info`

2023-01-24 15:30 UTC, mcaceres2017 commented on src.egg-info/top_level.txt
> +tests
Agregado con `src/src.egg-info`

2023-01-24 15:30 UTC, mcaceres2017 commented on src.egg-info/SOURCES.txt
> +tests/test_service.py
Agregado con `src/src.egg-info`

2023-01-24 15:42 UTC, mmolina2018 commented on text.txt
> +[[0.0177356731, -0.000204058073, 0.014053002, 10.4300003, 10.716876, 0.108766742, 1.63, 0.0, 33.9000015, 6.53999996, 5.42999983, 6.30000019, 2450019.71, 2452482.94]] ['RA', 'Dec', 'SideProb', 'Fpeak'
el test al llamar a service_get_conesearch() crea los archivos text y text2 para revisar la salida, dichos archivos ya fueron eliminados ya que finalmente eran un print que se me olvido borrar.

2023-01-24 17:05 UTC, mmolina2018 commented on text2.txt
> +{'RA': {'units': 'deg', 'values': [1.016179215453705]}, 'Dec': {'units': 'deg', 'values': [-0.011691666358472456]}, 'SideProb': {'units': ' ', 'values': [0.014053002]}, 'Fpeak': {'units': 'mJy', 'val
el test al llamar a service_get_conesearch() crea los archivos text y text2 para revisar la salida, dichos archivos ya fueron eliminados ya que finalmente eran un print que se me olvido borrar.

2023-01-30 13:13 UTC, dirodriguezm approved these changes

2023-01-30 14:13 UTC, dirodriguezm approved these changes

2023-01-30 14:13 UTC, merged